[33기 김민정] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/33-backend-westagram-1 pull request #15
Opened 2022-05-13 11:26 UTC by onlining

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
로그인엔드포인트구현
		 
## 수정 사항들 자세한 내용
로그인기능 구현

## 기타 질문 및 특이 사항
 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-05-14 05:16 UTC, jhwang0801 commented on students/minjeong/users/views.py
> +                return JsonResponse({"messages" : "NO_ID"}, status=400)
- 계정을 잘못 입력한 경우는 {"message": "INVALID_USER"}, status code 401 에러를 반환해야합니다.

2022-05-14 05:17 UTC, jhwang0801 commented on students/minjeong/users/views.py
> +                return JsonResponse({"messages" : "NOT_MATCH_PASSWORD"})
- 비밀번호를 잘못 입력한 경우에도 마찬가지로 {"message": "INVALID_USER"}, status code 401 에러를 반환해야합니다.

2022-05-14 05:35 UTC, onlining commented on students/minjeong/users/views.py
> +                return JsonResponse({"messages" : "NO_ID"}, status=400)
네

2022-05-14 05:36 UTC, onlining commented on students/minjeong/users/views.py
> +                return JsonResponse({"messages" : "NOT_MATCH_PASSWORD"})
{"message": "INVALID_PASSWORD"}로 바꾸는게 더 명확하지 않을까요.

2022-05-16 00:55 UTC, stresszero commented on students/minjeong/users/views.py
> +                return JsonResponse({"messages" : "INVALID_PASSWORD"})
비밀번호를 잘 못 입력한 경우 status code 401을 반환한다고 했는데 status 정보가 없네요

2022-05-16 00:55 UTC, stresszero commented on students/minjeong/users/views.py
> +            return JsonResponse({"message" : "SUCCESS"}, status=201)
로그인이 성공하면 status code 200을 반환한다고 합니다

2022-05-16 01:02 UTC, onlining commented on students/minjeong/users/views.py
> +                return JsonResponse({"messages" : "INVALID_PASSWORD"})
sㅔ

2022-05-16 01:02 UTC, onlining commented on students/minjeong/users/views.py
> +            return JsonResponse({"message" : "SUCCESS"}, status=201)
네

2022-05-16 03:24 UTC, ByeonghwiJeong reviewed
수정해야할것이 보이지않네요

2022-05-16 05:04 UTC, bigfanoftim requested changes

2022-05-16 05:04 UTC, bigfanoftim commented on students/minjeong/users/views.py
> +                return JsonResponse({"messages" : "INVALID_PASSWORD"}, status=400)
이메일과 패스워드를 한 번에 판단할 수 있지 않을까요?
```python
if not User.objects.filter(email = email, password = password).exists():
```

2022-05-16 05:20 UTC, onlining commented on students/minjeong/users/views.py
> +                return JsonResponse({"messages" : "INVALID_PASSWORD"}, status=400)
아이디는 있는데 비밀번호는 아니라고 알려줄 수 도 있어야 한다고 생각해서 그렇게 적어두기는 했는데 그럼 둘다 동일한 invalid_user를 내는 걸로 수정하는게 좋을까요?

2022-05-16 06:43 UTC, bigfanoftim commented on students/minjeong/users/views.py
> +                return JsonResponse({"messages" : "INVALID_PASSWORD"}, status=400)
민정님 다시 라벨 `수정 요청`으로 변경했습니다~ 수정 후 멘토 리뷰 요청으로 바꿔주세요~!

2022-05-16 08:08 UTC, bigfanoftim requested changes

2022-05-16 08:08 UTC, bigfanoftim commented on students/minjeong/users/views.py
> +            return JsonResponse({"message" : "INVALID_ID"}, status=400)
```suggestion
            return JsonResponse({"message" : "INVALID_EMAIL"}, status=400)
```

2022-05-16 08:22 UTC, bigfanoftim approved these changes
LGTM 👍

2022-05-16 08:22 UTC, merged