[33기 황재승] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/33-backend-westagram-1 pull request #17
Opened 2022-05-14 04:58 UTC by jhwang0801

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약

- 로그인 엔드포인트 구현
		 
## 수정 사항들 자세한 내용

- 이메일과 패스워드를 통해 로그인을 할 수 있음(사용자 계정과 비밀번호 필수)
    - 이메일이나 패스워드 정보가 전달되지 않는 경우, 에러(400)반환
    - 데이터 정보에 없는 이메일을 입력한 경우, 에러(401)반환
    - 혹은 이메일정보는 맞지만 패스워드가 잘못 입력된 경우, 에러(401)를 반환
    - 로그인이 성공한 경우, 200 SUCCESS 반환

## 기타 질문 및 특이 사항

- 다양한 웹사이트를 보면, 간단하게 이메일과 비밀번호의 정보만을 통해서 로그인을 진행하는 경우도 있지만, 계정에 해당하는 정보입력란에 이메일 대신 전화번호, 개인 Id를 통해서도 가능한 경우가 대다수인 것 같습니다.

어떻게 이메일이 아닌 다른 정보들(전화번호나 개인 id)로 같은 입력란을 통해 로그인이 가능한지 그리고 이 경우는 어떤식으로 코드를 짜야할지 궁금합니다.

개인적인 생각은 모델링에 해당 정보를 추가하고, SignIn 관련 View class에 가장 처음 if문으로 POST된 정보가 이메일, 전화번호, 혹은 개인 id인지 먼저 확인하는 절차를 걸치면 가능할 것이라 생각합니다만, 확신이 들지 않아서 질문 드립니다.

혹은 관련하여 통상적으로 더 많이 사용되고 정형화된 코딩기법이 있다면 알고 싶습니다.
감사합니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-05-14 05:34 UTC, onlining commented on students/jaeseung/users/views.py
> +
LGTM!~

2022-05-16 05:06 UTC, bigfanoftim requested changes

2022-05-16 05:06 UTC, bigfanoftim commented on students/jaeseung/users/views.py
> +                not User.objects.get(email=email).password == password:
이메일과 패스워드를 한 번에 필터링할 수 있습니다.
```python
if not User.objects.filter(email = email, password = password).exists():
```

2022-05-16 06:48 UTC, jhwang0801 commented on students/jaeseung/users/views.py
> +                not User.objects.get(email=email).password == password:
리뷰 감사합니다! 수정 완료했습니다~!

2022-05-16 08:09 UTC, bigfanoftim approved these changes
LGTM 👍 
코드가 정말 깔끔하네요 재승님!!

2022-05-16 08:09 UTC, merged