[33기 정병휘] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/33-backend-westagram-1 pull request #26
Opened 2022-05-18 01:56 UTC by ByeonghwiJeong

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 로그인 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- url: http://localhost:8000/user/login : POST Method 로그인
- (1) email & password 일치시 status 200 & 로그인성공
- (2) only email일치시 incorrect_password 메세지 Json Return
- (3) 나머지 케이스는 invalid_user

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- ❌ 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-05-18 04:42 UTC, jhwang0801 commented on students/byeonghwi/users/views.py
> +        return JsonResponse({'message':'invalid_user'}, status = 400)
Westudy에서 요구하는 것을 다시 확인하면,
계정과 비밀번호를 잘못한 경우 모두 동일하게 `{"message":"INVALID_USER"}, status code 401`을 반환하도록 하고 있습니다.
이 부분을 한번 다시 확인하시면 좋을것 같습니다!

2022-05-18 04:44 UTC, jhwang0801 commented on students/byeonghwi/users/views.py
> +        return JsonResponse({'message':'invalid_user'}, status = 400)
Westudy에서 요구하는 것을 다시 확인하면,
계정과 비밀번호를 잘못한 경우 모두 동일하게 `{"message":"INVALID_USER"}, status code 401`을 반환하도록 하고 있습니다.
이 부분을 한번 다시 확인하시면 좋을것 같습니다!

2022-05-18 04:44 UTC, stresszero commented on students/byeonghwi/users/views.py
> +        return JsonResponse({'message':'invalid_user'}, status = 400)
status code 401을 반환한다고 합니다

2022-05-18 04:54 UTC, ByeonghwiJeong commented on students/byeonghwi/users/views.py
> +        return JsonResponse({'message':'invalid_user'}, status = 400)
PR 감사합니다. 수정했습니다😄

2022-05-18 04:54 UTC, ByeonghwiJeong commented on students/byeonghwi/users/views.py
> +        return JsonResponse({'message':'invalid_user'}, status = 400)
PR 감사합니다. 수정했습니다😄

2022-05-18 04:59 UTC, stresszero commented on students/byeonghwi/users/views.py
> +        return JsonResponse({'message':'INVALID_USER'}, status = 401)
조건문 끝날때마다 빈줄을 넣으면 좋을것 같습니다
그리고 모든 케이스가 확인된다면 else가 없어도 될것 같습니다

2022-05-18 08:23 UTC, ByeonghwiJeong commented on students/byeonghwi/users/views.py
> +        return JsonResponse({'message':'INVALID_USER'}, status = 401)
감사합니다

2022-05-18 08:52 UTC, ByeonghwiJeong commented on students/byeonghwi/users/views.py
> +      return JsonResponse({'message':'SUCCESS'}, status = 200)
틀린조건 제거후 로그인형태로 수정했습니다

2022-05-18 21:54 UTC, ByeonghwiJeong commented on students/byeonghwi/users/views.py
> +      return JsonResponse({'message':'SUCCESS'}, status = 200)
@bigfanoftim 
위에서 부터 틀린조건(INVALED_USER, INCORRECT_PASSWORD) return 후
마지막에 if문없이 Login success return 형태로 
조건문 수정 완료했습니다.
감사합니다

2022-05-19 05:37 UTC, lordmyshepherd requested changes

2022-05-19 05:37 UTC, lordmyshepherd commented on students/byeonghwi/users/views.py
> +        return JsonResponse({'message':'INCORRECT_PASSWORD'}, status = 401)
아래 코드는 버그를 발생할 수 있는 코드입니다. password가 동일한 유저는 얼마든지 있을 수 있기 때문입니다.
그렇기 때문에 email과 password를 같이 조회해야 원하는 결과를 얻을 수 있습니다.

```suggestion
      if not User.objects.filter(email = email, password = password).exists():
        return JsonResponse({'message':'INCORRECT_PASSWORD'}, status = 401)
```

2022-05-19 06:20 UTC, ByeonghwiJeong commented on students/byeonghwi/users/views.py
> +        return JsonResponse({'message':'INCORRECT_PASSWORD'}, status = 401)
@lordmyshepherd 감사합니다 수정완료했습니다.

2022-05-19 06:54 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-05-19 06:54 UTC, merged